package views.administrador;

import com.mycompany.controllers.AdministradorController;
import com.mycompany.controllers.PacienteController;
import com.mycompany.models.PacienteModel;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author adria
 */
public class JanelaPacientes extends javax.swing.JFrame {

    private String cpfPaciente;

    /**
     * Creates new form DashboardAdministrador
     */
    public JanelaPacientes() {
        initComponents();
        Display();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonConsultas = new javax.swing.JButton();
        jButtonMedicos = new javax.swing.JButton();
        jButtonPacientes = new javax.swing.JButton();
        jButtonRelatorios = new javax.swing.JButton();
        jPanelExibirConteudos = new javax.swing.JPanel();
        jButtonCadastrarPacientes = new javax.swing.JButton();
        jButtonExcluirPacientes = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePacientes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButtonAtualizarPacientes = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldCPF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldTelefone = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldIdade = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldHistoricoMedico = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jButtonConsultas.setBackground(new java.awt.Color(204, 255, 255));
        jButtonConsultas.setForeground(new java.awt.Color(0, 51, 51));
        jButtonConsultas.setText("CONSULTAS");
        jButtonConsultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonConsultasMouseClicked(evt);
            }
        });

        jButtonMedicos.setBackground(new java.awt.Color(204, 255, 255));
        jButtonMedicos.setForeground(new java.awt.Color(0, 51, 51));
        jButtonMedicos.setText("MEDICOS");
        jButtonMedicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMedicosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonMedicosMouseEntered(evt);
            }
        });

        jButtonPacientes.setBackground(new java.awt.Color(204, 255, 255));
        jButtonPacientes.setForeground(new java.awt.Color(0, 51, 51));
        jButtonPacientes.setText("PACIENTES");

        jButtonRelatorios.setBackground(new java.awt.Color(204, 255, 255));
        jButtonRelatorios.setForeground(new java.awt.Color(0, 51, 51));
        jButtonRelatorios.setText("RELATORIOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRelatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jButtonConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButtonMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButtonPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButtonRelatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonCadastrarPacientes.setText("CADASTRAR");
        jButtonCadastrarPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCadastrarPacientesMouseClicked(evt);
            }
        });

        jButtonExcluirPacientes.setText("EXCLUIR");
        jButtonExcluirPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonExcluirPacientesMouseClicked(evt);
            }
        });

        jTablePacientes.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int row = jTablePacientes.rowAtPoint(e.getPoint());
                if (row >= 0) {
                    // Supondo que a coluna que contém o ID é a primeira (índice 0)
                    Object value = jTablePacientes.getValueAt(row, 1); // Ajuste o índice se necessário
                    if (value instanceof String) {
                        cpfPaciente = (String) value; // Captura como UUID
                        System.out.println("ID da consulta capturado: " + cpfPaciente); // Verificação do ID capturado
                    } else {
                        System.err.println("O valor não é um UUID: " + value);
                    }
                }
            }
        });
        jTablePacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NOME", "CPF", "IDADE", "TELEFONE", "HIST.. DE CONSULTAS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablePacientes);

        jLabel1.setText("NOME");

        jButtonAtualizarPacientes.setText("ATUALIZAR");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("PACIENTES CADASTRADOS NO SISTEMA");

        jLabel6.setText("CPF");

        jLabel7.setText("TELEFONE");

        jLabel2.setText("IDADE");

        jLabel3.setText("Historico medico");

        javax.swing.GroupLayout jPanelExibirConteudosLayout = new javax.swing.GroupLayout(jPanelExibirConteudos);
        jPanelExibirConteudos.setLayout(jPanelExibirConteudosLayout);
        jPanelExibirConteudosLayout.setHorizontalGroup(
            jPanelExibirConteudosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExibirConteudosLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(jPanelExibirConteudosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 836, Short.MAX_VALUE)
                    .addGroup(jPanelExibirConteudosLayout.createSequentialGroup()
                        .addGroup(jPanelExibirConteudosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelExibirConteudosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAtualizarPacientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonExcluirPacientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCadastrarPacientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelExibirConteudosLayout.createSequentialGroup()
                        .addGroup(jPanelExibirConteudosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanelExibirConteudosLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(245, 245, 245)
                                .addComponent(jLabel2))
                            .addGroup(jPanelExibirConteudosLayout.createSequentialGroup()
                                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)
                                .addGroup(jPanelExibirConteudosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldHistoricoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelExibirConteudosLayout.createSequentialGroup()
                                        .addComponent(jTextFieldIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(47, 47, 47)
                                        .addGroup(jPanelExibirConteudosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(134, 134, 134))
        );
        jPanelExibirConteudosLayout.setVerticalGroup(
            jPanelExibirConteudosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExibirConteudosLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelExibirConteudosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelExibirConteudosLayout.createSequentialGroup()
                        .addGroup(jPanelExibirConteudosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelExibirConteudosLayout.createSequentialGroup()
                                .addGroup(jPanelExibirConteudosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelExibirConteudosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelExibirConteudosLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanelExibirConteudosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelExibirConteudosLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelExibirConteudosLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldHistoricoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelExibirConteudosLayout.createSequentialGroup()
                        .addComponent(jButtonCadastrarPacientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAtualizarPacientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExcluirPacientes)))
                .addContainerGap(151, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelExibirConteudos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelExibirConteudos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMedicosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMedicosMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMedicosMouseEntered

    private void jButtonMedicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMedicosMouseClicked
        // TODO add your handling code here:
        JanelaMedicos janelaMedicos = new JanelaMedicos();
        janelaMedicos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonMedicosMouseClicked

    private void jButtonConsultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonConsultasMouseClicked
        // TODO add your handling code here:
        JanelaConsultas janelaConsultas = new JanelaConsultas();
        janelaConsultas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonConsultasMouseClicked

    private void jButtonCadastrarPacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCadastrarPacientesMouseClicked
        // TODO add your handling code here:
        String nome = jTextFieldNome.getText();
        String cpf = jTextFieldCPF.getText();
        // Obtém a idade como String e converte para int
        String idadeString = jTextFieldIdade.getText();
        int idade = Integer.parseInt(idadeString); // Converte a String para int
        String telefone = jTextFieldTelefone.getText();
        String historicomedico = jTextFieldHistoricoMedico.getText();
        List<String> listaHistoricoMedico = new ArrayList<>(Arrays.asList(historicomedico.split(","))); // Dividindo por vírgula, altere conforme necessário

        AdministradorController controllerAdmin = new AdministradorController();
        PacienteController pacienteController = new PacienteController();

        PacienteModel paciente = new PacienteModel(nome, cpf, idade, telefone, listaHistoricoMedico);
        pacienteController.cadastrarPaciente(paciente, controllerAdmin.buscarPeloEmail("JoedsonAdmin@gmail.com").getId());

    }//GEN-LAST:event_jButtonCadastrarPacientesMouseClicked

    private void jButtonExcluirPacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonExcluirPacientesMouseClicked
        // TODO add your handling code here:
        AdministradorController controllerAdmin = new AdministradorController();
        PacienteController pacienteController = new PacienteController();
        
        pacienteController.removerPaciente(cpfPaciente, controllerAdmin.buscarPeloEmail("JoedsonAdmin@gmail.com").getId());
    }//GEN-LAST:event_jButtonExcluirPacientesMouseClicked

    private void Display() {
        AdministradorController administradorController = new AdministradorController();
        PacienteController pacienteController = new PacienteController();
        List<PacienteModel> pacientes = pacienteController.listarPacientes(administradorController.buscarPeloEmail("JoedsonAdmin@gmail.com").getId());

        // Limpa a tabela antes de adicionar novos dados
        DefaultTableModel model = (DefaultTableModel) jTablePacientes.getModel();
        model.setRowCount(0);

        for (PacienteModel paciente : pacientes) {
            model.addRow(new Object[]{
                paciente.getNome(),
                paciente.getCPF(),
                paciente.getIdade(),
                paciente.getTelefone(),
                paciente.getHistóricoMedicoBasico()
            });
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPacientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizarPacientes;
    private javax.swing.JButton jButtonCadastrarPacientes;
    private javax.swing.JButton jButtonConsultas;
    private javax.swing.JButton jButtonExcluirPacientes;
    private javax.swing.JButton jButtonMedicos;
    private javax.swing.JButton jButtonPacientes;
    private javax.swing.JButton jButtonRelatorios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelExibirConteudos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePacientes;
    private javax.swing.JTextField jTextFieldCPF;
    private javax.swing.JTextField jTextFieldHistoricoMedico;
    private javax.swing.JTextField jTextFieldIdade;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldTelefone;
    // End of variables declaration//GEN-END:variables
}
